{
  "formatVersion": "1.1",
  "component": {
    "group": "com.paygen.sdk",
    "module": "paygen-sdk",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "paygen-sdk-1.1.2.aar",
          "url": "paygen-sdk-1.1.2.aar",
          "size": 180492,
          "sha512": "f095d9bfa041d2c7900147b9a21ec68e5bb7a1a7b75a62abaa611760c2bc9ff5e7dd3ae42500db5816d7b161d485d0669fb8ca2ddd0581686bf6a9dcad18b620",
          "sha256": "1a81841cd5aa5541df54489a1989adfcd7178414409b36759df5b559f4826bbc",
          "sha1": "3d963b624f35ef44fed23d2f0929ff0ad17e41cd",
          "md5": "340deb5966bd40b09d81b20db1d4eb09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "paygen-sdk-1.1.2.aar",
          "url": "paygen-sdk-1.1.2.aar",
          "size": 180492,
          "sha512": "f095d9bfa041d2c7900147b9a21ec68e5bb7a1a7b75a62abaa611760c2bc9ff5e7dd3ae42500db5816d7b161d485d0669fb8ca2ddd0581686bf6a9dcad18b620",
          "sha256": "1a81841cd5aa5541df54489a1989adfcd7178414409b36759df5b559f4826bbc",
          "sha1": "3d963b624f35ef44fed23d2f0929ff0ad17e41cd",
          "md5": "340deb5966bd40b09d81b20db1d4eb09"
        }
      ]
    }
  ]
}
